config/routes.rb
Rails.application.routes.draw do
  
  devise_for :customers, controllers: {
   sessions: 'customers/sessions',
   passwords: 'customers/passwords',
   registrations: 'customers/registrations'
   }
  
  scope module: :public do
   root 'homes#top'
   get 'about' => 'items#about'
  end
    
  namespace :public do
   delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
   resource :customers, only:[:show, :edit, :update]
   resources :items, only:[:index, :show]
   resources :addresses, only:[:index, :create, :update, :destroy, :edit]
   resources :cart_items, only:[:index, :create, :update, :destroy]
   resources :orders, only:[:new, :index, :show, :create]
   # ↓顧客の退会確認画面＆顧客の退会処理(ステータスの更新)
   get '/customers/unsubscribe' => 'customers#unsubscribe'
   patch '/customers/withdrawl' => 'customers#withdrawl'
   post '/orders/confirm' => 'orders#confirm'
   get '/oreders/complete' => 'orders#complete'
  end
  
  devise_for :admins, controllers: {
   sessions: 'admins/sessions',
   passwords: 'admins/passwords',
   registrations: 'admins/registrations'
   }
   
  namespace :admin do
   root :to => 'homes#top'
   resources :genres, only:[:index, :create, :edit, :update]
   resources :items, only:[:index, :new, :create, :show, :edit, :update]
   resources :customers, only:[:index, :show, :edit, :update]
   resources :orders, only:[:index, :show, :update]
   resources :order_details, only:[:update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 end

app/models/item.rb
class Item < ApplicationRecord
  attachment:image
  
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!,only: [:create,:edit,:update,:index, :show, :new]

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render "new"
    end

  end

  def edit
      @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
      flash[:notice_update] = "ジャンル情報を更新しました！"
    else
      redirect_to edit_admin_item_path(@item)
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :sales_status)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class='container'>
  <h2 class="edit-title">商品編集</h2>
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          <%= form_with model:@item, url:{action: 'update'}, local:true do |f|%>
          <div class="form-group">
            <label for="admin-name">Name</label>
            <%= f.text_field :name, class: "form-control name" %>
          </div>
          <div class="form-group">
            <label for="admin-image">商品写真</label>
            <%= f.attachment_field :image, class: "form-control-file item_image" %>
          </div>
          <div class="form-group">
            <label for="admin-introduction">商品説明</label>
            <%= f.text_area :introduction,  class: "form-control introduction" %>
          </div>
          <div class="form-group">
            <label for="price">税抜き価格</label>
            <%= f.text_area :price, class: "form-control introduction" %>
          </div>
          <div class="form-group">
            <label for="price">販売ステータス</label>
            <%= f.select :sales_status,{'販売中':false, '販売休止/売り切れ':true}, { class: 'form-control',required: false} %>
          </div>          
          <div class="form-group">
            <%= f.submit"更新", class: "btn btn-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
</div>

app/views/admin/items/index.html.erb
<div class="row">
        <h2>商品一覧</h2>
        
        <table class="table table-success table-striped">
          <thead>
            <tr class="active">
              <th>商品名</th>
              <th>商品単価</th>
              <!--<th>ジャンル</th>-->
              <th>販売ステータス</th>
              <th></th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @items.each do |item|%>
              <tr>
                <td><%= link_to item.name, admin_item_path(item.id)  %></td>
                <td><%= item.price %></td>
                <!--<td>%= item.genre.name %</td>-->
                <td>
                <% if item.sales_status == false %>
                販売中
                <% else %>
                販売休止/売り切れ
                <% end %>
                </td>
                <td><%= link_to "商品詳細", admin_item_path(item) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <%= link_to '新規登録', new_admin_item_path, class: "btn btn-success" %>
    <%= paginate @items %>
    </div>

app/views/admin/items/new.html.erb
<h2 class= 'mt-3'>商品新規登録画面</h2>
<div class = 'row'>
    <%= form_with model:@item, url: admin_items_path, local: true do |f| %>
      <div class='form-group'>
        <label for='item_name'>NAME</label>
        <%= f.text_field :name, class: "form-control name", placeholder: 'name' %>
      </div>
      <div class="form-group">
        <label for = "item_image">商品写真</label>
          <%= f.attachment_field :image, class: "form-control-file item_image"%>
      </div>
      <div class="form-group">
        <label for ='item_genre'>ジャンル</label><br>
          <%= f.collection_select :genre_id, Genre.all, :id, :name %>
          <!-- f.collection_select(プロパティ名, オブジェクトの配列, value属性の項目, 表示テキストの項目) -->
          <!-- Genre.allでジャンルのテーブル内情報を持ってきてる -->
      </div>
      <div class="form-group">
        <label for = "item_introduciton">商品説明</label>
          <%= f.text_area :introduction, class: "form-control-file item_introduction", placeholder: 'content' %>
      </div>
      <div class="form-group">
        <label for = "item_price">税抜き価格</label>
          <%= f.text_field :price, class: "form-control-file item_price", placeholder: 'price' %>
      </div>
      <div class="form-group">
        <%= f.label :sales_status, '販売ステータス' %>
        <%= f.select :sales_status, {'販売中':false, '販売休止/売り切れ':true}, { class: 'form-control',required: false} %>
      <div class='form-group'>
        <%= f.submit '新規登録', class: 'btn btn-success' %>
      </div>
    <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="row">
      <h2>商品詳細</h2>
      <table class="table">
        <thead>
          <tr>
            <th>NAME</th>
            <th>商品写真</th>
            <th>商品説明</th>
            <th>税抜価格</th>
            <th>販売ステータス</th>
            <th>編集</th>
          </tr>
        </thead>
        <tbody>

          <tr class="table-active">
            <td><%= @item.name %></td>
            <td><%= attachment_image_tag @item, :image, :fill, 100, 100, format: 'jpeg' %></td>
            <td><%= @item.introduction%></td>
            <td><%= @item.price%></td>
            <td><% if @item.sales_status == false %>
            販売中
            <% else %>
            販売休止/売り切れ
            <% end %>
            </td>
            <td><%= link_to '編集ボタン', edit_admin_item_path %></td>
          </tr>

        </tbody>
      </table>
</div>