config/routes.rb
Rails.application.routes.draw do
  
  devise_for :customers, controllers: {
   sessions: 'customers/sessions',
   passwords: 'customers/passwords',
   registrations: 'customers/registrations'
   }
  
  scope module: :public do
   root 'homes#top'
   get 'about' => 'items#about'
  end
    
  namespace :public do
   delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
   resource :customers, only:[:show, :edit, :update]
   resources :items, only:[:index, :show]
   resources :addresses, only:[:index, :create, :update, :destroy, :edit]
   resources :cart_items, only:[:index, :create, :update, :destroy]
   resources :orders, only:[:new, :index, :show, :create]
   # ↓顧客の退会確認画面＆顧客の退会処理(ステータスの更新)
   get '/customers/unsubscribe' => 'customers#unsubscribe'
   patch '/customers/withdrawl' => 'customers#withdrawl'
   post '/orders/confirm' => 'orders#confirm'
   get '/oreders/complete' => 'orders#complete'
  end
  
  devise_for :admins, controllers: {
   sessions: 'admins/sessions',
   passwords: 'admins/passwords',
   registrations: 'admins/registrations'
   }
   
  namespace :admin do
   root :to => 'homes#top'
   resources :genres, only:[:index, :create, :edit, :update]
   resources :items, only:[:index, :new, :create, :show, :edit, :update]
   resources :customers, only:[:index, :show, :edit, :update]
   resources :orders, only:[:index, :show, :update]
   resources :order_details, only:[:update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum payment_method: {クレジットカード:0, 銀行振込:1} 
  enum status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  

  def index
    @search = Order.ransack(params[:q])
    @orders = @search.result
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id]) #注文詳細の特定
  	@order_details = @order.order_details #注文から紐付く商品の取得
  	@order.update(order_params) #注文ステータスの更新

 	  if @order.status == "入金確認" #注文ステータスが入金確認なら下の事をする
	     @order_details.each do |order_detail|
        order_detail.make_status = "製作待ち"
        order_detail.save
      end
	     #製作ステータスを「製作待ちに」　更新
	     #もし、ステータスが入金確認であれば、order.detailsを全て、制作待ちで更新する。
	  end
  		 redirect_to  admin_order_path(@order) #注文詳細に遷移
  end
    # こっちでも可能
    # emunの変換前取得している
  	# if @order.read_attribute_before_type_cast(:order_status) == 1
  	# 	@order_items.each do |order_item|
  	# 	order_item.update(making_status: 1)
  	# 	end
   #  end
  private

  def order_params
  	params.require(:order).permit(:status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <h2>注文一覧</h2>
    <div class="order-table">
      <table class="table">
        <thead>
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td><%= link_to order.created_at.strftime("%Y-%m-%d %H:%M:%S"), admin_order_path(order) %></td>
              <td><%= order.customer.last_name + "　" + order.customer.first_name %></td>
              <td><%= order.order_details.sum(:amount) %></td>
              <td><%= order.status %></td>
            </tr>
            <% end %>
            <!--%= paginate @orders %-->
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="pull-right">
	<%= search_form_for @search, url: admin_orders_path do |f| %>
		<%= f.label :name, "注文履歴キーワード" %>
		<%= f.search_field :name_cont %>
		<%= f.submit '検索' %>
	<% end %>
</div>

app/views/admin/orders/show.html.erb
<div class="container takasa">
  <div class="row">
    <div class="col-xs-12">
      <h2>注文履歴詳細</h2>
      <!-- 購入詳細情報 -->
      <table>
       <tr>
        <th class= "order-show">購入者</th>
        <td><%= @order.customer.last_name %> <%= @order.customer.first_name %></td>
      </tr>
      <tr>
        <th class= "order-show">注文日時</th>
        <td><%= @order.created_at.strftime("%Y-%m-%d")  %></td>
      </tr>
      <tr>
        <th class= "order-show">配送先</th>
        <td>〒<%= @order.postal_code %> <%= @order.address %></td>
      </tr>
      <tr>
        <th class= "order-show">支払い方法</th>
        <td><%= @order.payment_method %></td>
      </tr>
      <tr>

        <!-- 注文ステータス変更　プルダウン　更新を押すとアップデート -->
        <th>注文ステータス</th>
        <td>
          <%= form_for @order, url: {action: 'update' } do |f| %><!--order controllerのupdateの飛ぶ-->
          　<%= f.select :status,["入金待ち","入金確認","製作中","発送準備中","発送済"] ,style: "margin-top:10px;#" %><!--ステータス選択 -->
            <%= f.submit "更新" ,class: "btn btn-primary btn-sm" %></td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
  <div class="orders-show">
    <div class=" col-xs-9">
      <table class="table ">
        <tr>
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
          <th></th>
        </tr>
        <%  @order_details.each do |order_detail| %><!--注文した商品の履歴一覧をeach分で表示　-->
        <tr>
          <td><%= order_detail.item.name %></td>
          <td><%= order_detail.price_including_tax %></td>
          <td><%= order_detail.amount %></td>
          <td><%= (order_detail.price_including_tax * order_detail.amount) %> </td>
        <!-- 製作ステータス変更　更新を押すと更新-->
          <%= form_for order_detail, url: admin_order_detail_path(order_detail) do |f| %>
          <td><%= f.select :making_status,["着手不可","製作待ち","製作中","製作完了"] %></td><!--ステータス選択 -->
          <td><%= f.submit "更新" ,class:"btn btn-primary btn-xs" %></td>
          <% end %>
        </tr>
        <tbody>
          <td><h4>商品合計: ¥<%= order_detail.price_including_tax %>円</h4></td>
          <td><h4>送料:　¥<%= @order.shipping_cost %>円</h4></td>
          <td><h4>請求金額合計: ¥<%= (order_detail.price_including_tax + @order.shipping_cost) %>円</h4></td>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>