config/routes.rb
Rails.application.routes.draw do
  
  devise_for :customers, controllers: {
   sessions: 'customers/sessions',
   passwords: 'customers/passwords',
   registrations: 'customers/registrations'
   }
  
  scope module: :public do
   root 'homes#top'
   get 'about' => 'items#about'
  end
    
  namespace :public do
   delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
   resource :customers, only:[:show, :edit, :update]
   resources :items, only:[:index, :show]
   resources :addresses, only:[:index, :create, :update, :destroy, :edit]
   resources :cart_items, only:[:index, :create, :update, :destroy]
   resources :orders, only:[:new, :index, :show, :create]
   # ↓顧客の退会確認画面＆顧客の退会処理(ステータスの更新)
   get '/customers/unsubscribe' => 'customers#unsubscribe'
   patch '/customers/withdrawl' => 'customers#withdrawl'
   post '/orders/confirm' => 'orders#confirm'
   get '/oreders/complete' => 'orders#complete'
  end
  
  devise_for :admins, controllers: {
   sessions: 'admins/sessions',
   passwords: 'admins/passwords',
   registrations: 'admins/registrations'
   }
   
  namespace :admin do
   root :to => 'homes#top'
   resources :genres, only:[:index, :create, :edit, :update]
   resources :items, only:[:index, :new, :create, :show, :edit, :update]
   resources :customers, only:[:index, :show, :edit, :update]
   resources :orders, only:[:index, :show, :update]
   resources :order_details, only:[:update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def full_address
    '〒' + self.postal_code + ' ' + self.address + ' ' + self.name
  end
  
  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  validates :amount, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  enum status: {会員: 0, 退会: 1}
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  # 退会
  def active_for_authentication?
    super && (self.withdrawl_active == true)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  validates :name, presence:true
end

app/models/item.rb
class Item < ApplicationRecord
  attachment:image
  
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum payment_method: {クレジットカード:0, 銀行振込:1} 
  enum status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: {着手不可:0, 製作待ち:1, 製作中:2, 製作完了:3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def index
    @genres = Genre.all
    @genre =  Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    end
  end
  
  private 
  
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
   from = Date.current.beginning_of_day
   to = Date.current.end_of_day
   @order = Order.where(created_at: from..to)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!,only: [:create,:edit,:update,:index, :show, :new]

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render "new"
    end

  end

  def edit
      @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
      flash[:notice_update] = "ジャンル情報を更新しました！"
    else
      redirect_to edit_admin_item_path(@item)
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :sales_status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
   case resource
    when Customer
     root_path
    when Admin
    admin_root_path
   end
  end

  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :withdrawl_active])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <!--↓headerの背景色を変更する-->
      <nav class = "navbar navbar-expand-lg navbar-dark bg-dark">
        <%= link_to "TOPページ", root_path, class: "navbar-brand" %>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class = "collapse navbar-collapse"  id="navbarNavDropdown" >
            <ul class = "navbar-nav ml-auto">

              <% if admin_signed_in? %>
                <li><%= link_to "商品一覧", admin_items_path, class: "fas fa-candy-cane nav-link text-light" %></li>
                <li><%= link_to "会員一覧", admin_customers_path, class: "fas fa-users nav-link text-light" %></li>
                <li><%= link_to "注文一覧履歴", admin_orders_path, class: "fas fa-book-open nav-link text-light" %></li>
                <li><%= link_to "ジャンル一覧", admin_genres_path, class: "fas fa-cookie-bite nav-link text-light" %></li>
                <li><%= link_to "ログアウト",  destroy_admin_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %></li>
              <% elsif customer_signed_in? %>
                <li><%= link_to "マイページ", public_customers_path, class: "fas fa-user nav-link text-light" %></li>
                <li><%= link_to "商品一覧", public_items_path, class: "fas fa-list nav-link text-light" %></li>
                <li><%= link_to "注文一覧履歴", public_orders_path, class: "fas fa-book-open nav-link text-light" %></li>
                <li><%= link_to "カート", public_cart_items_path, class: "fas fa-book-open nav-link text-light" %></li>
                <li><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %></li>
              <% else %>
                <li><%= link_to "商品一覧", public_items_path, class: "fas fa-users nav-link text-light" %></li>
                <!--<li><%= link_to "About", class: "fas fa-users nav-link text-light" %></li>-->
                <li><%= link_to "新規登録", new_customer_registration_path,  class: "fas fa-link nav-link text-light" %></li>
                <li><%= link_to "ログイン", new_customer_session_path, class: "fas fa-user-plus nav-link text-light" %></li>
              <% end %>
            </ul>
          </div>
      </nav>
    </header>
  <div class= 'container'>
    <%= yield %>
  </div>
  </body>
</html>